### ISSUE TITLE
'core:cancel'  jQuery::trigger can no longer be used to listen for Atom commands.

### ISSUE THREAD

**Issue by theexec** [akonwi/apm-publish#6]
Package still works just displays a deprecation alert. I wanted to pass it along, Great package.

atom core (1 deprecation)
Are you trying to listen for the 'core:cancel' Atom command with jQuery::on? jQuery::trigger can no longer be used to listen for Atom commands. Please use atom.commands.add instead. See the docs at https://atom.io/docs/api/latest/CommandRegistry#instance-add for details.

Object.add - C:\Users\name\.atom\packages\apm-publish\node_modules\space-pen\lib\space-pen.js:592:14
<unknown> - C:\Users\name\.atom\packages\apm-publish\node_modules\jquery\dist\jquery.js:4861:17
Function.each - C:\Users\name\.atom\packages\apm-publish\node_modules\jquery\dist\jquery.js:374:23
jQuery.each - C:\Users\name\.atom\packages\apm-publish\node_modules\jquery\dist\jquery.js:139:17
jQuery.on - C:\Users\name\.atom\packages\apm-publish\node_modules\jquery\dist\jquery.js:4860:15
OutputView.subscribeWith - C:\Users\name\.atom\packages\apm-publish\node_modules\emissary\lib\subscriber.js:28:32

**Comment by akonwi** [comment]
Thanks! I've removed that code in the new version.
